runtime: python27
api_version: 1
threadsafe: true
service: default

skip_files:
- node_modules
- src

handlers:
- url: /
  static_files: public/index.html
  upload: public/index.html
 
- url: /(.*)
  static_files: public/\1
  upload: public/(.*)